export const inventory = [
  {
      area: [[1, 1]],
      canLay: false,
      canSit: false,
      canStack: false,
      canWalk: false,
      currentState: 0,
      id: 2,
      possibleStates: [0],
      type: 'floor',
      name: '4_noob_plant_noob_plant',
    },
    {
      area: [[1, 1]],
      canLay: false,
      canSit: false,
      canStack: false,
      canWalk: false,
      currentState: 0,
      id: 2,
      possibleStates: [0],
      type: 'floor',
      name: '4_noob_plant_noob_plant',
    },
    {
      area: [[1, 1]],
      canLay: false,
      canSit: false,
      canStack: false,
      canWalk: false,
      currentState: 0,
      id: 2,
      possibleStates: [0],
      type: 'floor',
      name: '4_noob_plant_noob_plant',
    },
    {
      area: [[1, 1]],
      canLay: false,
      canSit: false,
      canStack: false,
      canWalk: false,
      currentState: 0,
      id: 2,
      possibleStates: [0],
      type: 'floor',
      name: '4_noob_plant_noob_plant',
    },
    {
      area: [[1, 1]],
      canLay: false,
      canSit: false,
      canStack: false,
      canWalk: false,
      currentState: 0,
      id: 2,
      possibleStates: [0],
      type: 'floor',
      name: '4_noob_plant_noob_plant',
    },
]
